{{- if .Values.global.ory.hydra.persistence.postgresql.enabled }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "ory.fullname" . }}-gcloud-sqlproxy
spec:
  host: {{ template "ory.fullname" . }}-gcloud-sqlproxy.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end}}