---
monitoring:
  enabled: true
  dashboards:
    enabled: true
  istioServiceMonitor:
    enabled: true
    scrapeInterval: ""

global:
  istio:
    gateway:
      name: kyma-gateway
      namespace: kyma-system
    mtlsGateway:
      name: kyma-mtls-gateway
      namespace: kyma-system
