apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
{{ include "api-gateway.labels" . | indent 4 }}
